# Generated by Django 4.1.3 on 2022-12-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_teacher_name_alter_teacher_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_active',
        ),
    ]
