# Generated by Django 4.1.3 on 2022-12-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_teacher_is_active'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table=None,
        ),
    ]
